function drawFox(s, col, acc) {
  ctx.fillStyle = col;
  ctx.fillRect(-8*s, -10*s, 16*s, 20*s);
  ctx.beginPath();
  ctx.moveTo(-8*s, -10*s); ctx.lineTo(-7*s, -20*s); ctx.lineTo(-1*s, -10*s);
  ctx.fill();
  ctx.beginPath();
  ctx.moveTo(1*s, -10*s); ctx.lineTo(7*s, -20*s); ctx.lineTo(8*s, -10*s);
  ctx.fill();
  ctx.fillStyle = '#222';
  ctx.beginPath();
  ctx.moveTo(-6*s, -10*s); ctx.lineTo(-6*s, -16*s); ctx.lineTo(-2*s, -10*s);
  ctx.fill();
  ctx.beginPath();
  ctx.moveTo(2*s, -10*s); ctx.lineTo(6*s, -16*s); ctx.lineTo(6*s, -10*s);
  ctx.fill();
  ctx.fillStyle = '#fff';
  ctx.beginPath();
  ctx.moveTo(-5*s, -2*s); ctx.lineTo(0, 2*s); ctx.lineTo(5*s, -2*s);
  ctx.lineTo(5*s, 5*s); ctx.lineTo(-5*s, 5*s);
  ctx.fill();
  ctx.fillStyle = '#fff';
  ctx.fillRect(-6*s, -7*s, 4*s, 4*s);
  ctx.fillRect(2*s, -7*s, 4*s, 4*s);
  ctx.fillStyle = '#000';
  ctx.fillRect(-4*s, -6*s, 2*s, 3*s);
  ctx.fillRect(4*s, -6*s, 2*s, 3*s);
  ctx.fillStyle = '#222';
  ctx.fillRect(-1*s, -1*s, 2*s, 2*s);
  ctx.fillStyle = col;
  ctx.beginPath();
  ctx.moveTo(8*s, 4*s);
  ctx.quadraticCurveTo(18*s, -4*s, 14*s, -12*s);
  ctx.quadraticCurveTo(10*s, -6*s, 8*s, 2*s);
  ctx.fill();
  ctx.fillStyle = '#fff';
  ctx.beginPath();
  ctx.arc(14*s, -10*s, 3*s, 0, Math.PI*2);
  ctx.fill();
}
